/* ============================================================
   CASE FILE Nº 2026-PM — content data
   Everything the board renders lives here. Edit freely:
   positions are board coordinates (x right, y up), sizes in
   board units. Threads connect card pins bottom-up: earliest
   experience at the bottom, each string labeled with the
   skill that transferred forward.
   ============================================================ */

window.CASE_DATA = {
  meta: {
    caseNo: "CASE Nº 2026-PM",
    codename: "THE FAST LEARNER",
    tagline:
      "Subject enters unfamiliar technical domains and ships working systems within hours. Range observed: heliophysics to bioinformatics. Motive: curiosity. Pattern: repeat offender.",
  },

  regions: [
    { id: "subject", label: "Subject", y: 122 },
    { id: "trail", label: "The Trail", y: 52 },
    { id: "evidence", label: "Evidence", y: -46 },
    { id: "mo", label: "M.O.", y: -104 },
    { id: "tipline", label: "Tip Line", y: -142 },
  ],

  cards: [
    /* ---------- SUBJECT PROFILE ---------- */
    {
      id: "banner",
      region: "subject",
      type: "banner",
      pos: [0, 136],
      rot: -0.4,
      w: 62, h: 13,
      title: "THE FAST LEARNER",
      sub: "CASE Nº 2026-PM · STATUS: ACTIVE · JURISDICTION: EVERY DOMAIN AT ONCE",
    },
    {
      id: "profile",
      region: "subject",
      type: "report",
      pos: [-17, 113],
      rot: -1.2,
      w: 26, h: 22,
      title: "SUBJECT PROFILE",
      lines: [
        "NAME ....... MAHESHWARI, PRINCY",
        "BASE ....... ATLANTA, GEORGIA",
        "STATUS ..... B.S. COMPUTER SCIENCE,",
        "             GEORGIA STATE UNIVERSITY",
        "             PRESIDENTIAL SCHOLAR (FULL RIDE)",
        "GPA ........ 4.25 / 4.3",
        "",
        "KNOWN BEHAVIOR: enters a field she has",
        "never touched — reads the literature,",
        "learns the tooling, ships a working",
        "system. Time to competence is measured",
        "in hours, not semesters.",
        "",
        "RANGE OBSERVED: deep learning theory,",
        "heliophysics, computer vision, LLM",
        "systems, women's health AI,",
        "bioinformatics.",
      ],
      stamp: "UNDER INVESTIGATION",
      detail: {
        heading: "Subject profile",
        body: [
          "Princy Maheshwari is a Computer Science student and researcher at Georgia State University on a full-ride Presidential Scholarship (GPA 4.25/4.3).",
          "The through-line of this case file is not any single result — it is speed of adaptation. Every exhibit on this board comes from a different domain: solar physics, computer vision, developer tooling, women's health, bioinformatics. In each one the subject went from zero background to a working, measured system in a matter of hours to weeks.",
          "Follow the red threads on the Trail: each one marks a skill acquired in one domain and carried into the next.",
        ],
        links: [
          { label: "GitHub", href: "https://github.com/princymaheshwari" },
          { label: "LinkedIn", href: "https://www.linkedin.com/in/princy-maheshwari1/" },
        ],
      },
    },
    {
      id: "mugshot",
      region: "subject",
      type: "polaroid",
      pos: [15, 112],
      rot: 2.4,
      w: 15, h: 18,
      img: "assets/Princy_pic.jpg",
      caption: "the subject — last known photo",
      pinColor: 0x2b4a73,
    },
    {
      id: "howto",
      region: "subject",
      type: "note",
      pos: [30, 124],
      rot: -3,
      w: 13, h: 10,
      hand: ["scroll to descend", "the board — click", "anything pinned", "to read the file"],
    },

    /* ---------- THE TRAIL (bottom = earliest) ---------- */
    {
      id: "trail-plaque",
      region: "trail",
      type: "banner",
      pos: [-36, 96],
      rot: 0.8,
      w: 30, h: 9,
      title: "THE TRAIL",
      sub: "READ BOTTOM-UP · EARLIEST AT THE FLOOR · STRINGS = WHAT CARRIED FORWARD",
    },
    {
      id: "bioinfo",
      region: "trail",
      type: "lead",
      pos: [8, 84],
      rot: -1.6,
      w: 21, h: 14,
      title: "THE GENOME CASE",
      date: "MAY 2026 · BIOINFORMATICS · MEYER LAB, LEHIGH",
      lines: [
        "Summer Research Software",
        "Engineer, STEM-SI Scholar.",
        "Building convgeno: a Python CLI",
        "that packs a hand-stitched",
        "genomics workflow into one",
        "Nextflow DAG on any SLURM",
        "cluster. ~13,000-task job",
        "arrays vs a ~63h benchmark.",
      ],
      stamp: "ACTIVE",
      pinColor: 0x7e1f24,
      detail: {
        heading: "The genome case — bioinformatics",
        body: [
          "The newest domain jump on record: from satellite time-series to computational biology. Summer Research Software Engineer in the Meyer Lab at Lehigh University (STEM-SI Scholar), May 2026 – present.",
          "The subject is building convgeno, a Python CLI that automates a multi-stage genomics analysis workflow biologists currently run by hand-stitching separate tools and writing cluster jobs one by one — packaged as a portable pipeline that runs end-to-end on any SLURM cluster.",
          "The pipeline is orchestrated as a DAG with workflow managers such as Nextflow, integrating multiple bioinformatics tools into one reproducible workflow deployable on HPC clusters with zero manual job-wiring. Optimized for scale and portability: ~13,000 independent tasks distributed as parallel SLURM job arrays, cutting a benchmark run down from ~63 hours.",
          "Domain entered: computational biology and HPC. Background carried in: the data-pipeline and normalization instincts built in the solar case.",
        ],
        links: [],
      },
    },
    {
      id: "veritas",
      region: "trail",
      type: "index",
      pos: [-28, 64],
      rot: 1.8,
      w: 19, h: 10.5,
      title: "VERITAS.DEV",
      date: "NexHacks 2026 · LLM SYSTEMS",
      lines: [
        "GitHub App catching code—doc",
        "drift. 3-layer hybrid: AST",
        "parsing, embedding routing,",
        "LLM compare. Cost cut 88%,",
        "accuracy held at 92%.",
      ],
      detail: {
        heading: "Veritas.dev — dev tooling / LLM systems",
        body: [
          "An AI-powered GitHub App that detects when code changes drift from their documentation. A 3-layer hybrid system — multi-language parsing (Python AST, JS/TS), semantic routing via sentence-transformer embeddings, and LLM comparison — files automated GitHub issues to keep docs honest.",
          "Adaptive routing reduced LLM cost by 88% while maintaining 92% accuracy.",
          "Domain entered: LLM orchestration and developer tooling. Background carried in: GPU inference pipelines from ToolFinder.",
        ],
        links: [{ label: "View on Devpost", href: "https://devpost.com/software/kmfo" }],
      },
    },
    {
      id: "toolfinder",
      region: "trail",
      type: "index",
      pos: [30, 60],
      rot: -2.2,
      w: 19, h: 10.5,
      title: "TOOLFINDER",
      date: "HackIllinois 2026 · COMPUTER VISION",
      lines: [
        "Voice-driven object search in",
        "cluttered workspaces. YOLO +",
        "SAM2 in parallel on Modal GPUs.",
        "87% mAP@50 · 88.4% precision",
        "· 82.6% recall.",
      ],
      detail: {
        heading: "ToolFinder — multimodal computer vision",
        body: [
          "Voice-driven object search for cluttered workspaces. A GPU-accelerated inference pipeline on Modal orchestrates speech transcription, semantic query mapping, and parallel vision models — a custom-trained YOLO detector and SAM2 segmentation — returning pixel-precise masks and coordinates in real time.",
          "87% mAP@50, 88.4% precision, 82.6% recall.",
          "Domain entered: production computer vision. Background carried in: the MediaPipe pose work from NutriGirl.",
        ],
        links: [{ label: "View on Devpost", href: "https://devpost.com/software/the-byte-la016n" }],
      },
    },
    {
      id: "sep",
      region: "trail",
      type: "report",
      pos: [-1, 42],
      rot: 1.1,
      w: 21, h: 13,
      title: "THE SOLAR CASE",
      date: "OCT 2025 · HELIOPHYSICS · DATA MINING LAB, GSU",
      lines: [
        "Math Path Scholar w/ Prof.",
        "Berkay Aydin. Pipeline detecting",
        "solar particle events in 30 yrs",
        "of GOES/SOHO telemetry. 100%",
        "recall, 92.4% precision. Found",
        "bugs in NASA's own archives.",
      ],
      stamp: "SOLVED",
      detail: {
        heading: "The solar case — heliophysics",
        body: [
          "As a Math Path Research Scholar in GSU's Data Mining Lab (advisor: Prof. Berkay Aydin), the subject built an end-to-end pipeline detecting Solar Energetic Particle events across 30 years of multi-mission satellite data (GOES, SOHO).",
          "Instrument-specific adapters, satellite-year fallback logic, normalization deriving integral proton flux across three GOES generations — validated at 100% recall (159/159 known events) and 92.4% precision. Along the way she debugged inconsistencies in NASA's own legacy archives.",
          "Domain entered: space physics, with zero prior background. Background carried in: neural sequence modeling from the RA post.",
        ],
        links: [{
          label: "View on GitHub",
          href: "https://github.com/princymaheshwari/solar-energetic-particle-event-detection-pipeline#1-objective",
        }],
      },
    },
    {
      id: "ra",
      region: "trail",
      type: "index",
      pos: [-33, 24],
      rot: -1.4,
      w: 19, h: 10.5,
      title: "RESEARCH ASSISTANT",
      date: "AUG 2025 · DEEP LEARNING · CS DEPT, GSU",
      lines: [
        "Zero-shot & weak supervision",
        "methods w/ Prof. Venkateswara.",
        "CNNs for spatial data, RNNs for",
        "sequences — learning that",
        "generalizes from few labels.",
      ],
      detail: {
        heading: "Undergraduate Research Assistant — deep learning",
        body: [
          "Research on zero-shot and weak-supervision learning with Prof. Hemanth Venkateswara, Dept. of Computer Science, GSU. Building neural networks with TensorFlow and NumPy — CNN-based spatial processing and RNN-based sequence modeling — aimed at workflows that generalize with minimal labeled data.",
          "Fittingly, the research subject is itself the case's theme: learning fast from very little.",
        ],
        links: [],
      },
    },
    {
      id: "nutrigirl",
      region: "trail",
      type: "index",
      pos: [31, 20],
      rot: 2.6,
      w: 19, h: 10.5,
      title: "NUTRIGIRL AI",
      date: "2025 · HEALTH AI · HACKHER GSU",
      lines: [
        "2nd overall + 2nd health track.",
        "PCOS/PCOD platform: lab report",
        "analyzer, MediaPipe pose-",
        "corrected workouts, voice",
        "coaching. Led backend + CV.",
      ],
      stamp: "2ND PLACE",
      detail: {
        heading: "NutriGirl AI — women's health",
        body: [
          "2nd Overall and 2nd in the Health Track at HackHer GSU 2025. An AI platform for women managing PCOS/PCOD: lab report interpretation, nutrition tracking, and pose-aware workout coaching.",
          "The subject led backend and computer vision — a smart lab analyzer for blood reports and a MediaPipe-based pose detection system with real-time, voice-guided form correction (OpenAI APIs, Web Speech API, Node/Express).",
          "Domain entered: health tech, first hackathon. Background carried in: CS fundamentals from GSU coursework.",
        ],
        links: [{ label: "View on Devpost", href: "https://devpost.com/software/nutrigirl-ai" }],
      },
    },
    {
      id: "gsu",
      region: "trail",
      type: "index",
      pos: [0, 4],
      rot: -0.8,
      w: 21, h: 9.5,
      title: "ORIGIN: GEORGIA STATE",
      date: "AUG 2025 · WHERE THE TRAIL STARTS",
      lines: [
        "B.S. Computer Science, class of",
        "2029. Presidential Scholar on a",
        "full ride. GPA 4.25/4.3. Math,",
        "ML, and an alarming appetite",
        "for new problems.",
      ],
      pinColor: 0xb08d4f,
      detail: {
        heading: "Origin — Georgia State University",
        body: [
          "B.S. in Computer Science, Aug 2025 – May 2029. Presidential Scholar on a full-ride merit scholarship, GPA 4.25/4.3.",
          "Relevant training records: Code Path AI110 (Foundations of AI Engineering), CSC 1301/1302 (Principles of CS I & II), Calculus I & II, Discrete Mathematics.",
          "Everything above this card on the board traces back here.",
        ],
        links: [],
      },
    },

    /* ---------- EVIDENCE LOCKER ---------- */
    {
      id: "evidence-plaque",
      region: "evidence",
      type: "banner",
      pos: [-32, -16],
      rot: -0.6,
      w: 34, h: 9,
      title: "EVIDENCE LOCKER",
      sub: "PHYSICAL EXHIBITS · SCREENSHOTS ADMITTED INTO RECORD",
    },
    {
      id: "ex-sep",
      region: "evidence",
      type: "photo",
      pos: [-27, -40],
      rot: 1.6,
      w: 24, h: 21,
      img: "assets/sep_pipeline.png",
      tag: "EXHIBIT A",
      caption: "the solar case — validation table",
      detailRef: "sep",
    },
    {
      id: "ex-toolfinder",
      region: "evidence",
      type: "photo",
      pos: [27, -36],
      rot: -2.1,
      w: 24, h: 21,
      img: "assets/toolfinder.png",
      tag: "EXHIBIT B",
      caption: "toolfinder — masks on the workbench",
      detailRef: "toolfinder",
    },
    {
      id: "ex-veritas",
      region: "evidence",
      type: "photo",
      pos: [-27, -66],
      rot: -1.2,
      w: 24, h: 21,
      img: "assets/Veritas.png",
      tag: "EXHIBIT C",
      caption: "veritas.dev — drift, caught",
      detailRef: "veritas",
    },
    {
      id: "ex-nutrigirl",
      region: "evidence",
      type: "photo",
      pos: [27, -70],
      rot: 2.3,
      w: 24, h: 21,
      img: "assets/nutrigirl_ai.png",
      tag: "EXHIBIT D",
      caption: "nutrigirl ai — 2nd place, hackher",
      detailRef: "nutrigirl",
    },

    /* ---------- M.O. ---------- */
    {
      id: "mo-card",
      region: "mo",
      type: "report",
      pos: [-16, -104],
      rot: -1,
      w: 26, h: 15,
      title: "MODUS OPERANDI",
      lines: [
        "ML/AI ..... PyTorch, TensorFlow,",
        "            LangGraph, Anthropic SDK,",
        "            Hugging Face, scikit-learn",
        "BACKEND ... Python, FastAPI,",
        "            Node.js, Express",
        "DATA ...... PostgreSQL, MongoDB,",
        "            NumPy, Pandas, Supabase",
        "FRONTEND .. TypeScript, React,",
        "            Tailwind CSS",
        "INFRA ..... Docker, Git, Modal",
      ],
      stamp: "KNOWN METHODS",
      detail: {
        heading: "Modus operandi — the toolkit",
        body: [
          "The subject's known methods, recovered from repositories and testimony: PyTorch, TensorFlow, LangGraph and the Anthropic SDK for ML and agentic systems; Python/FastAPI and Node/Express backends; PostgreSQL, MongoDB and the NumPy/Pandas stack for data; TypeScript and React up front; Docker, Git and Modal underneath.",
          "Tools change per case. The pattern — learn fast, ship, measure — does not.",
        ],
        links: [{ label: "GitHub — @princymaheshwari", href: "https://github.com/princymaheshwari" }],
      },
    },
    {
      id: "witness",
      region: "mo",
      type: "note",
      pos: [16, -100],
      rot: 2.2,
      w: 16, h: 12,
      hand: [
        "witness statement:",
        "“she learned our whole",
        "stack over a weekend",
        "and fixed the bug by",
        "monday.” — anonymous",
      ],
    },

    /* ---------- TIP LINE ---------- */
    {
      id: "tip-plaque",
      region: "tipline",
      type: "banner",
      pos: [0, -128],
      rot: 0.5,
      w: 36, h: 9,
      title: "TIP LINE",
      sub: "WANNA BUILD SOMETHING TECHNICALLY AMBITIOUS? CONTACT ME BELOW.",
    },
  ],

  /* threads: from earlier card -> later card, label = what transferred */
  threads: [
    { from: "gsu", to: "ra", label: "math + ML foundations" },
    { from: "gsu", to: "nutrigirl", label: "CS fundamentals, first build" },
    { from: "ra", to: "sep", label: "sequence models → telemetry" },
    { from: "nutrigirl", to: "toolfinder", label: "pose CV → vision pipelines" },
    { from: "toolfinder", to: "veritas", label: "GPU inference → LLM routing", tagT: 0.3 },
    { from: "sep", to: "bioinfo", label: "signal processing → sequence data", tagT: 0.72 },
  ],
};
